name: book_summary
description: "Book Summary Project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9 
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.4 
  quickalert: ^1.0.2 
  cached_network_image: ^3.3.1
  firebase_core: ^2.27.0
  font_awesome_flutter: ^10.7.0  
  carousel_slider: ^4.2.1  
  mssql_connection: ^1.1.3
  ionicons: ^0.2.2
  restart_app: ^1.2.1
  localization: ^2.1.1
  flutter_localizations:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  image_picker: ^1.0.8
  dropdown_button2: ^2.3.9
  mask_text_input_formatter: ^2.9.0

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/resource/language/
