// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsgNSIGw4h9KOTllDZtDCY0DNVFWFPy08',
    appId: '1:496424333114:web:9053549f04cfc538952a03',
    messagingSenderId: '496424333114',
    projectId: 'bookapp-f6413',
    authDomain: 'bookapp-f6413.firebaseapp.com',
    storageBucket: 'bookapp-f6413.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOZA1lJZuRv0q4bQ7Er_nhKV_KyqOcqek',
    appId: '1:496424333114:android:558e7f7af0d48cc7952a03',
    messagingSenderId: '496424333114',
    projectId: 'bookapp-f6413',
    storageBucket: 'bookapp-f6413.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRGEo__j58wJVEn357gPd7k_r4yQZ64ko',
    appId: '1:496424333114:ios:5dc9e84c99eaee69952a03',
    messagingSenderId: '496424333114',
    projectId: 'bookapp-f6413',
    storageBucket: 'bookapp-f6413.appspot.com',
    iosBundleId: 'com.example.bookSummary',
  );
}
